apiVersion: kpack.io/v1alpha2
kind: Image
metadata:
  name: harbor-to-gitlab-image
  namespace: builds
spec:
  tag: harbor.home.starkenberg.net/library/harbor-to-gitlab
  serviceAccountName: kpack-service-account
  builder:
    name: my-cluster-builder
    kind: ClusterBuilder
  source:
    git:
      url: https://git.home.starkenberg.net/bstarke/harbor-to-gitlab
      revision: main
